apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      securityContext:
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        rm -rf $(workspaces.source.path)/*
        rm -rf $(workspaces.source.path)/.[!.]*
        rm -rf $(workspaces.source.path)/..?*
        
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Perintah lengkap yang mau dijalankan
      type: string
      default: "nosetests -v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        # Jalankan args secara langsung sebagai perintah shell
        $(params.args)